apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "viya4-home-dir-builder.fullname" . }}
  labels:
    {{- include "viya4-home-dir-builder.labels" . | nindent 4 }}
data:
  VIYA_BASE_URL: {{ .Values.viya.baseUrl | quote }}
  CLIENT_ID: {{ .Values.oauth.clientId | quote }}
  HOME_DIR_PATH: {{ .Values.viya.homeDirLocation | quote }}
  USER_EXCEPTIONS: {{ .Values.viya.userExceptions | quote }}
  DEBUG: {{ .Values.debug | quote }}
  DRY_RUN: {{ .Values.dryRun | quote }}
