apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "selerity-home-dir-builder.fullname" . }}
data:
  VIYA_BASE_URL: "{{ .Values.viya.base_url }}"
  CLIENT_ID: "{{ .Values.oauth.client_id }}"
  HOME_DIR_PATH: "{{ .Values.viya.home_dir_location }}"
  USER_EXCEPTIONS: "{{ .Values.viya.user_exceptions }}"
  DEBUG: "{{ .Values.debug }}"