apiVersion: v1
kind: Secret
metadata:
  name: {{ include "viya4-home-dir-builder.fullname" . }}
  labels:
    {{- include "viya4-home-dir-builder.labels" . | nindent 4 }}
  annotations:
    "helm.sh/resource-policy": "keep"
type: Opaque
{{- $secretName := (include "viya4-home-dir-builder.fullname" .) }}
{{- $existingSecret := (lookup "v1" "Secret" .Release.Namespace $secretName) | default dict }}
{{- $existingData := (get $existingSecret "data") | default dict }}
{{- $clientSecret := (get $existingData "CLIENT_SECRET" | b64dec) | default (randAlphaNum 32) }}
stringData:
  CLIENT_SECRET: {{ $clientSecret | quote }}
