{{- $client_secret := "" }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "selerity-home-dir-builder.fullname" . }}
  annotations:
    "helm.sh/resource-policy": "keep"
type: Opaque
stringData:
  {{- $secret := (lookup "v1" "Secret" .Release.Namespace "{{ include \"selerity-home-dir-builder.fullname\" . }}") | default dict }}
  {{- $client_secret := (get $secret "{{ include \"selerity-home-dir-builder.fullname\" . }}") | default (randAlphaNum 32 | b64enc) }}
  CLIENT_SECRET: {{ $client_secret }}