sas:
  order: "TEST"
  registryPass: "TEST"
  license: "TEST"

image:
  repository: nginx
  pullPolicy: IfNotPresent
  tag: "latest"

initImage:
  repository: alpine
  tag: "3.21"
  pullPolicy: IfNotPresent

probe:
  port: http
  path: /index.html

service:
  port: 8080
  type: ClusterIP
