# Default values for selerity-home-dir-builder.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

image:
  repository: selerity/python-core
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: latest

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

schedule: 0,15,30,45 * * * *
# If suspend is set to true, then you must manually trigger the job
# If suspend is set to false, then the job will run on the schedule above
suspend: true
debug: 0
dry_run: 1

viya:
  # The base URL of SAS Viya. e.g. https://viya.company.com
  base_url: https://viya.company.com
  # The location within the container to mount the home directories to
  home_dir_location: /home
  # A comma separated list of user ids you do not want home directories for
  user_exceptions: Administrator

nfs:
  # Host name of the NFS Server hosting the home directories
  server: nfs.company.com
  # The location on the NFS server that has the home directories
  mount: /home

oauth:
  client_id: selerity.homedir_builder

nodeSelector: {}

tolerations: []

affinity: {}
