viya:
  baseUrl: "https://viya.example.com"
  homeDirLocation: /home
  userExceptions: Administrator

nfs:
  server: "nfs.example.com"
  mount: /home

oauth:
  clientId: test.client

image:
  repository: python
  pullPolicy: IfNotPresent
  tag: 3.12-slim
