apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "sas-analytics-pro.fullname" . }}-init-files
data:
  {{- $files := .Files }}
  {{- range tuple "boot.sh" }}
  {{ . }}: |+
        {{- $files.Get . | nindent 4 }}
  {{- end }}