{{- if and .Values.sas.orderCertFile (not .Values.sas.registryPass) }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "sas-analytics-pro.fullname" . }}-pull-secret-sa
  labels:
    {{- include "sas-analytics-pro.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-10"
    "helm.sh/hook-delete-policy": hook-succeeded,before-hook-creation
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "sas-analytics-pro.fullname" . }}-pull-secret-role
  labels:
    {{- include "sas-analytics-pro.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-10"
    "helm.sh/hook-delete-policy": hook-succeeded,before-hook-creation
rules:
  - apiGroups: [""]
    resources: ["secrets", "configmaps"]
    verbs: ["get", "create", "update"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "sas-analytics-pro.fullname" . }}-pull-secret-rb
  labels:
    {{- include "sas-analytics-pro.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-10"
    "helm.sh/hook-delete-policy": hook-succeeded,before-hook-creation
subjects:
  - kind: ServiceAccount
    name: {{ include "sas-analytics-pro.fullname" . }}-pull-secret-sa
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: {{ include "sas-analytics-pro.fullname" . }}-pull-secret-role
  apiGroup: rbac.authorization.k8s.io
{{- end }}
