apiVersion: v1
kind: Secret
metadata:
  name: {{ include "sas-analytics-pro.fullname" . }}-pull-secret
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ template "imagePullSecret" . }}