apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ template "sas-analytics-pro.fullname" . }}-order
  labels:
    {{- include "sas-analytics-pro.labels" . | nindent 4 }}
stringData:
{{- if .Values.sas.order }}
  order: {{ .Values.sas.order }}
{{- end }}
{{- if .Values.sas.registryPass }}
  registrySecret: {{ .Values.sas.registryPass }}
{{- end }}
{{- if .Values.sas.ordersApiKey }}
  ordersApiKey: {{ .Values.sas.ordersApiKey | b64enc }}
{{- end }}
{{- if .Values.sas.ordersApiSecret }}
  ordersApiSecret: {{ .Values.sas.ordersApiSecret | b64enc }}
{{- end }}
{{- if .Values.sas.cadenceName }}
  cadenceName: {{ .Values.sas.cadenceName }}
{{- end }}
{{- if .Values.sas.cadenceVersion }}
  cadenceVersion: {{ .Values.sas.cadenceVersion }}
{{- end }}
data:
  certs.zip: |
    {{ .Values.sas.orderCertFile | b64enc | nindent 4 }}