{{- $userPassword := (include "sas-analytics-pro.sasUserPassword" .) -}}
{{- $randomPassword := (randAlphaNum 10) -}}
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ template "sas-analytics-pro.fullname" . }}-authconfig
  labels:
    {{- include "sas-analytics-pro.labels" . | nindent 4 }}
stringData:
  user: {{ template "sas-analytics-pro.sasUser" . }}
  password: {{ default $randomPassword $userPassword }}
  authinfo.txt: |
    default user {{ template "sas-analytics-pro.sasUser" . }} password {{ default $randomPassword $userPassword }}