apiVersion: v2
name: sas-analytics-pro
description: A Helm chart to deploy SAS Analytics Pro
home: https://selerity.com.au
icon: https://assets.selerity.com.au/brand/icons/icon_selerity_purple.png
maintainers:
  - name: seleritymichael
    email: michael.dixon@selerity.com.au

type: application

version: 1.3.3

appVersion: "0.18.30-20220920.1663692624971"
